# Generated by Django 4.2 on 2026-05-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ARapp", "0002_realm_content_and_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentitem",
            name="icon",
            field=models.CharField(
                default="sword",
                help_text="模板用键，如 sword / core，避免 4 字节 emoji 写入非 utf8mb4 表",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="loot",
            name="icon_code",
            field=models.CharField(
                default="BOX", max_length=50, verbose_name="图标代号(避免 MySQL utf8 存 emoji)"
            ),
        ),
    ]
