# Generated by Django 4.2 on 2026-05-13 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ARapp", "0004_userprofile_private_realm"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="icon_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ASCII 短标，如 OASIS / GEM，避免 emoji 入库",
                max_length=20,
                verbose_name="HUD 短标",
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AddField(
            model_name="mission",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AddField(
            model_name="mission",
            name="target_event",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="与 /api/progress/event/ 的 event 对齐；空则不由事件推进",
                max_length=80,
                verbose_name="进度事件键",
            ),
        ),
        migrations.CreateModel(
            name="UserEventStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(db_index=True, max_length=80)),
                ("count", models.PositiveIntegerField(default=0)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "event")},},
        ),
    ]
