# Generated by Django 4.2 on 2026-03-21 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "loot_type",
                    models.CharField(
                        choices=[
                            ("Material", "基础材料"),
                            ("Texture", "贴图碎片"),
                            ("Core", "能量核心"),
                            ("Blueprint", "武器图纸"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("Common", "普通"),
                            ("Rare", "稀有"),
                            ("Epic", "史诗"),
                            ("Legendary", "传说"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_price", models.IntegerField(default=100, verbose_name="商店回收价")),
                (
                    "icon_code",
                    models.CharField(default="📦", max_length=50, verbose_name="图标符号"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Realm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="位面名称")),
                ("description", models.TextField(verbose_name="位面描述")),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("Common", "普通"),
                            ("Rare", "稀有"),
                            ("Epic", "史诗"),
                            ("Legendary", "传说"),
                        ],
                        default="Common",
                        max_length=20,
                    ),
                ),
                (
                    "bonus_effect",
                    models.CharField(
                        help_text="例如: 物理防御 +15%", max_length=100, verbose_name="战斗加成"
                    ),
                ),
                (
                    "preview_color",
                    models.CharField(
                        default="#00f2ff", max_length=7, verbose_name="预览色(HEX)"
                    ),
                ),
                (
                    "is_unlocked_default",
                    models.BooleanField(default=False, verbose_name="是否默认解锁"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                ("combat_power", models.IntegerField(default=1000)),
                ("credits", models.IntegerField(default=500, verbose_name="信用点(货币)")),
                (
                    "current_realm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ARapp.realm",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="持有数量"),
                ),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ARapp.loot"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "用户背包",
                "unique_together": {("user", "loot")},
            },
        ),
    ]
