# Generated by Django 4.2 on 2026-05-11 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ARapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_key", models.CharField(db_index=True, max_length=40)),
                ("category_title", models.CharField(max_length=120)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("rarity", models.CharField(default="COMMON", max_length=20)),
                ("reward_exp", models.PositiveIntegerField(default=0)),
                ("reward_credits", models.PositiveIntegerField(default=0)),
                ("reward_note", models.CharField(blank=True, max_length=200)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={"ordering": ["category_key", "sort_order", "id"],},
        ),
        migrations.CreateModel(
            name="EquipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("weapon_main", "主武器"),
                            ("weapon_off", "副武器"),
                            ("armor", "护甲"),
                            ("core", "技能核心"),
                            ("mobility", "移动装置"),
                            ("cosmetic", "外观"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("Common", "普通"),
                            ("Rare", "稀有"),
                            ("Epic", "史诗"),
                            ("Legendary", "传说"),
                        ],
                        default="Rare",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("icon", models.CharField(default="⚔️", max_length=32)),
                (
                    "power_bonus",
                    models.PositiveIntegerField(default=0, verbose_name="战力加成展示值"),
                ),
                ("stat_label_1", models.CharField(blank=True, max_length=50)),
                ("stat_value_1", models.CharField(blank=True, max_length=50)),
                ("stat_label_2", models.CharField(blank=True, max_length=50)),
                ("stat_value_2", models.CharField(blank=True, max_length=50)),
                (
                    "is_default_loadout",
                    models.BooleanField(default=False, verbose_name="新用户默认装入此槽位"),
                ),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={"ordering": ["sort_order", "id"],},
        ),
        migrations.CreateModel(
            name="MarketProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("price_credits", models.PositiveIntegerField(default=0)),
                (
                    "image_placeholder",
                    models.CharField(
                        default="IMG_DATA_LOST", max_length=80, verbose_name="占位图文字"
                    ),
                ),
                (
                    "accent",
                    models.CharField(
                        blank=True, help_text="cyan / purple / 空，用于前端样式类", max_length=20
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["sort_order", "id"],},
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(help_text="稳定键，如 awaken_link", unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("main", "主线"),
                            ("daily", "日常"),
                            ("weekly", "周常"),
                            ("side", "支线"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "target",
                    models.PositiveIntegerField(default=1, verbose_name="目标进度值"),
                ),
                ("reward_exp", models.PositiveIntegerField(default=0)),
                ("reward_credits", models.PositiveIntegerField(default=0)),
                ("reward_item_label", models.CharField(blank=True, max_length=120)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={"ordering": ["sort_order", "id"],},
        ),
        migrations.CreateModel(
            name="UserMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可接"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ARapp.mission"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_missions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "mission")},},
        ),
        migrations.CreateModel(
            name="UserEquippedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("weapon_main", "主武器"),
                            ("weapon_off", "副武器"),
                            ("armor", "护甲"),
                            ("core", "技能核心"),
                            ("mobility", "移动装置"),
                            ("cosmetic", "外观"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ARapp.equipmentitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipped_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "slot")},},
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ARapp.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "achievement")},},
        ),
    ]
