# Generated by Django 4.2 on 2026-05-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ARapp", "0003_icon_keys_ascii_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_title",
            field=models.CharField(default="初始接入者", max_length=100, verbose_name="称号"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="exp",
            field=models.PositiveIntegerField(default=0, verbose_name="经验值"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="private_realm_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="room_template / material_pack / lighting / decorations 等",
                verbose_name="私人位面配置",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="realm_space_level",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="私人位面空间等级"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="realm_visibility",
            field=models.CharField(
                choices=[("private", "私有"), ("friends", "好友"), ("public", "公开")],
                default="private",
                max_length=20,
                verbose_name="私人位面访问权限",
            ),
        ),
    ]
